---
version: '3'

services:
  postgres:
    image: docker.io/library/postgres:15.1-alpine
    container_name: boilerplate-postgres
    hostname: postgres
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    networks:
      - workbench
    restart: unless-stopped

volumes:
  postgresql-data:
    driver: local

networks:
  workbench:
    name: workbench
