---
version: '3'

services:
  mongodb:
    image: docker.io/library/mongo:7.0.5
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
      - type: volume
        source: mongodb-configdb
        target: /data/configdb
    environment:
      # MONGO_INITDB_ROOT_USERNAME:
      # MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
    command: --bind_ip_all --replSet rs0
    ports:
      - target: 27017
        published: $MONGODB_PORT
        protocol: tcp
    restart: unless-stopped
    healthcheck:
      test: echo "try {rs.status()} catch (err) {rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]})}" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 30
      start_period: 0s
      start_interval: 1s

volumes:
  mongodb-data:
    driver: local
  mongodb-configdb:
    driver: local
