---
version: '3'

services:
  redis:
    image: docker.io/library/redis:7.2.3-alpine
    volumes:
      - type: volume
        source: redis-data
        target: /data
    ports:
      - target: 6379
        published: $REDIS_PORT
        protocol: tcp
    restart: unless-stopped
  postgres:
    image: docker.io/library/postgres:15.1-alpine
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - target: 5432
        published: $POSTGRES_PORT
        protocol: tcp
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  postgresql-data:
    driver: local
