---
version: '3'

services:
  mongodb:
    image: docker.io/library/mongo:6.0.13
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
      - type: volume
        source: mongodb-configdb
        target: /data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
    ports:
      - target: 27017
        published: $MONGODB_PORT
        protocol: tcp
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local
  mongodb-configdb:
    driver: local
