---
version: '3'

services:
  app:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    image: ghcr.io/brunowego/nestjs-with-prisma:latest
    container_name: boilerplate-app
    volumes:
      - type: bind
        source: ./
        target: /workspace
        consistency: cached
    environment:
      DATABASE_URL:
    command: tail -f /dev/null
    network_mode: service:postgres
    restart: unless-stopped
    depends_on:
      - postgres
