// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'br' | 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  search: {
    /**
     * S​e​a​r​c​h
     */
    label: string
    /**
     * S​e​a​r​c​h​.​.​.
     */
    placeholder: string
  }
  widget: {
    /**
     * N​e​w​ ​W​i​d​g​e​t
     */
    new: string
  }
  locale: {
    /**
     * S​e​l​e​c​t​ ​a​ ​L​a​n​g​u​a​g​e
     */
    label: string
  }
}

export type TranslationFunctions = {
  search: {
    /**
     * Search
     */
    label: () => LocalizedString
    /**
     * Search...
     */
    placeholder: () => LocalizedString
  }
  widget: {
    /**
     * New Widget
     */
    new: () => LocalizedString
  }
  locale: {
    /**
     * Select a Language
     */
    label: () => LocalizedString
  }
}

export type Formatters = {}
