import LoginButton from '@/components/LoginButton'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
  // const { data: data } = useSession()

  return (
    <>
      <Head>
        <title>Boilerplate with Cerbos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginButton />

        {/* {data && <pre>{JSON.stringify(data, null, 2)}</pre>} */}
      </main>
    </>
  )
}
