---
name: Docker Build and Push (nestjs-with-prisma-rest)

on:
  push:
    branches:
      - nestjs-with-prisma-rest
    paths:
      - .github/workflows/docker-image.yml
      - db/**
      - src/**
      - .dockerignore
      - Dockerfile
      - nest-cli.json
      - package.json
      - pnpm-lock.yaml
      - tsconfig*.json
  pull_request:
    branches:
      - nestjs-with-prisma-rest
    paths:
      - .github/workflows/docker-image.yml
      - db/**
      - src/**
      - .dockerignore
      - Dockerfile
      - nest-cli.json
      - package.json
      - pnpm-lock.yaml
      - tsconfig*.json
  workflow_dispatch:

concurrency:
  group: boilerplates

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/nestjs-with-prisma-rest'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Short SHA
        id: sha
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c 1-8)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./
          push: ${{ github.ref == 'refs/heads/nestjs-with-prisma-rest' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}
            ghcr.io/${{ github.repository }}:latest
